server.port: 8081

spring:
  datasource:
    url:jdbc:postgresql://localhost:5432/loja?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username:fernan
    password:root
    driver-class-name:org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true